# 
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.32
# 

Name:       wordgrinder

# >> macros
# << macros

Summary:    Cell word processor
Version:    0.8
Release:    0
Group:      Applications
License:    MIT
URL:        http://cowlark.com/wordgrinder/index.html
Source0:    %{name}-%{version}.tar.gz
Source100:  wordgrinder.yaml
Source101:  wordgrinder-rpmlintrc
Patch0:     makefile.patch
Patch1:     desktop.patch
BuildRequires:  pkgconfig(freetype2)
BuildRequires:  pkgconfig(ncursesw)
BuildRequires:  pkgconfig(lua)
BuildRequires:  pkgconfig(minizip)
BuildRequires:  pkgconfig(zlib)
BuildRequires:  ninja
BuildRequires:  desktop-file-utils

%description

WordGrinder is a simple, Unicode-aware word processor that runs on the
console. It's designed to get the hell out of your way and let you write;
it does very little, but what it does it does well.

It supports basic paragraph styles, basic character styles, basic screen
markup, a menu interface that means you don't have to remember complex
key sequences, HTML import and export, and some other useful features.

%if "%{?vendor}" == "chum"
Title: WordGrinder
Type: console-application
DeveloperName: David Given
PackagerName: nephros
Categories:
  - Office
  - WordProcessor
Custom:
  Repo: https://github.com/davidgiven/wordgrinder
  PackagingRepo: https://github.com/sailfishos-chum/wordgrinder
PackageIcon: https://github.com/davidgiven/wordgrinder/blob/master/extras/icon.png
Screenshots:
  - http://cowlark.com/wordgrinder/AF1QipP6k5K-t8kryec2t71jxChQWS6hTuFr8Qu3CHs9.jpg
  - http://cowlark.com/wordgrinder/AF1QipNpWXJ028DQWnn9KNZkZQCPXSxHHfxECYVXZOmN.jpg
Url:
  Homepage: %{url}
  Help: https://gist.github.com/davidgiven/1aba97e96a9b8f9b573b
%endif


%prep
%setup -q -n %{name}-%{version}/upstream

# makefile.patch
%patch0 -p1
# desktop.patch
%patch1 -p1
# >> setup
# << setup

%build
# >> build pre
make %{?_smp_mflags} PREFIX=%{buildroot}%_prefix
# << build pre



# >> build post
# << build post

%install
rm -rf %{buildroot}
# >> install pre
%make_install PREFIX=%{buildroot}%_prefix
%__install -m 644 -D extras/icon.png %{buildroot}%{_datadir}/icons/hicolor/256x256/apps/%{name}.png
# << install pre

# >> install post
rm -rf %{buildroot}%{_mandir}
rm -rf %{buildroot}%{_docdir}
rm -rf %{buildroot}%{_datadir}/pixmaps
# << install post

desktop-file-install --delete-original       \
  --dir %{buildroot}%{_datadir}/applications             \
   %{buildroot}%{_datadir}/applications/*.desktop

%files
%defattr(-,root,root,-)
%{_bindir}/*
%{_datadir}/applications/%{name}.desktop
%{_datadir}/icons/*/*/apps/%{name}.png
%{_datadir}/mime-info/*
# >> files
# << files
